import Head from "next/head";
import FrontPageHeader from "../components/FrontPageHeader";
import Footer from "../components/Footer";
import { AppShell } from "@mantine/core";
import Cart from "../components/cart/Cart";

export default function Home() {
  return (
    <>
      <Head>
        <title>MakeupByS</title>
        <meta name="theme-color" content="#000000"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <AppShell fixed={false} header={<FrontPageHeader />} footer={<Footer />}>
        <>
          <main style={{ marginTop: 60, minHeight: "100vh" }}>
            <h1>Startsida</h1>
          </main>
          <Cart />
        </>
      </AppShell>
    </>
  );
}
