GET http://localhost:3000/api/color

###

GET http://localhost:3000/api/color/6395c57998499264aa6727c0


### 

POST  http://localhost:3000/api/admin/color
Content-Type: application/json

{
    "hexcolor": "#af9f90",
    "colorTag": "63a86db32622fa2566183512",
    "seasons": ["63a8715e2622fa256618352d"]
}

###

PUT  http://localhost:3000/api/admin/color/#FFFFF
Content-Type: application/json

{
"hexcolor": "#a7a045", "colorTag": "63776c45770d0813197325ba", "season": ["63775ce666fff92f5e0ca446"]
}

###

DELETE  http://localhost:3000/api/admin/color/6395c57998499264aa6727c0


