GET http://localhost:3000/api/open/subproduct

###


POST http://localhost:3000/api/open/subproduct/search
Content-Type: application/json

{
    "value": "make up"
}

###


GET http://localhost:3000/api/open/subproduct/mykonos


### 

POST  http://localhost:3000/api/admin/subproduct
Content-Type: application/json

{
    "mainProduct": "63a9b167acc13b27eb7a973b",
    "title": "testigen2",
    "images": ["OWEYOUNOTHING.webp", "OWEYOUNOTHING-2.webp"],
    "colors": ["63a877702622fa2566183687"],
    "availableQty": 100
}

###

PUT  http://localhost:3000/api/admin/subproduct/63abfe2d6d1641449b9cd0f5
Content-Type: application/json

{
    "_id": "63abfe2d6d1641449b9cd0f5",
   "mainProduct": "63a9b167acc13b27eb7a973b",
    "title": "testigen2updated",
    "images": ["OWEYOUNOTHING.webp", "OWEYOUNOTHING-2.webp"],
    "colors": ["63a877702622fa2566183687"],
    "availableQty": 100
}

###

DELETE  http://localhost:3000/api/admin/subproduct/63abfde72012206f0c3ed9e6


