GET http://localhost:3000/api/open/colortag

###

GET http://localhost:3000/api/open/colortag/gray

###

POST  http://localhost:3000/api/admin/colortag
Content-Type: application/json

{
    "color": "Brun",
    "hexcolor": "#643F11"
}

###

PUT  http://localhost:3000/api/admin/colortag/gray
Content-Type: application/json

{
"_id": "638b0fdbab81ffdb7675e4e6",
"color": "hittepå",
"hexcode": "#D8d8d8"
}

###

DELETE  http://localhost:3000/api/admin/colortag/gray
Content-Type: application/json

