GET http://localhost:3000/api/admin/users

###

GET http://localhost:3000/api/admin/users/63ab2d016ed1683c22c2c149

###

GET http://localhost:3000/api/customer/user/63ab2d016ed1683c22c2c149

###

DELETE  http://localhost:3000/api/admin/users/63ab2d016ed1683c22c2